version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency-base
    working_dir: /usr/src/myapp
    container_name: nest-authentication-authorization-container
    restart: unless-stopped

    volumes:
      - ./:/usr/src/myapp

    stdin_open: true
    ports:
      - "${APP_PORT:-80}:3000"
      - "${PRISMA_STUDIO_PORT:-5555}:5555"
      - "9229:9229"

    networks:
      - diego-network
  
  postgres:
    container_name: nest-authentication-authorization-postgress
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123
    networks:
      - diego-network

  mongo:
    image: "mongo:6.0"
    container_name: nest-authentication-authorization-mongodb
    restart: unless-stopped
    logging:
      driver: none
    ports:
      - "${DB_PORT_INTERNAL_LOCALHOST_MONGODB:-27017}:${DB_PORT_MONGODB:-27017}"
    environment:
      - MONGODB_DATABASE="vf-read-db"
    networks:
      - diego-network

networks:
  diego-network:
    external:
      name: diego-shared-network
